# Generated by Django 3.2.5 on 2021-11-13 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_post_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-posted_on']},
        ),
    ]
